# -*- coding: utf-8 -*-
"""Eligibility Criteria_roberta-base-squad2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKB-iqGqD9YITk3e60R8fJz7OsbC3NAk
"""

!pip install transformers torch

from transformers import pipeline

#pre trained Q-A model
qa_pipeline = pipeline("question-answering",model="deepset/roberta-base-squad2")

from transformers import pipeline
import json
import re

# Load the QA pipeline
qa_pipeline = pipeline("question-answering")

# Load and clean JSON data
with open("grants.json", "r", encoding="utf-8") as file:
    json_text = file.read()
json_text = re.sub(r"[\x00-\x1F\x7F]", "", json_text)  
grants_data = json.loads(json_text)
print("JSON loaded successfully!")

questions = [
    "Who can apply for this grant?",
    "Is your organization in the following sector?",
    "The minimum funding amount is?",
    "Requirements for the Grant",
    ""
]

for grant in grants_data[:30]:
    program_name = grant.get("program_name", "Program Name not mentioned")
    description = grant.get("description", "") or "No description provided"
    
    print(f"Grant: {program_name}")

    eligibility_answers = []
    for q in questions:
        if description.strip():
            result = qa_pipeline({"question": q, "context": description})
            eligibility_answers.append(result.get('answer', 'No answer found'))
        else:
            eligibility_answers.append("No description available")

    for q, a in zip(questions, eligibility_answers):
        print(f"{q} -> {a}")

