# -*- coding: utf-8 -*-
"""GrantProposal_first_draft

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cVccdD_HUbAssblYEHE62KcVQzDxuoU
"""

import torch

from transformers import AutoModelForCausalLM, AutoTokenizer

from transformers import pipeline
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

grant_pipeline = pipeline("text2text-generation",model="google/flan-t5-large")
model_name = "google/flan-t5-large"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name, device_map="auto", torch_dtype=torch.float16)

def generate_text(prompt, max_new_tokens=500):
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model.generate(**inputs, max_new_tokens=max_new_tokens, temperature=0.8, top_p=0.9)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Collect user inputs
project_title = input("Enter Project Title: ")
applicant_name = input("Enter Applicant/Organization Name: ")
mission_statement = input("Enter Organization's Mission Statement: ")
problem_statement = input("Describe the problem your project addresses: ")
goals = input("What are the main goals of your project? ")
planned_activities = input("What activities will you undertake? ")
timeline = input("What is the estimated timeline? ")
expected_outcomes = input("What are the expected outcomes? ")

statement_of_need_example = """
Many low-income communities struggle with limited access to quality education and job opportunities, which creates a cycle of poverty. This grant aims to address these disparities by providing essential resources, training, and support programs to uplift underprivileged groups. The project will empower individuals by giving them the tools they need to become self-sufficient and break the cycle of poverty.
"""

project_description_example = """
This project will focus on providing skill-based education and vocational training programs to underserved communities. By establishing learning centers, we aim to enhance employment opportunities and economic independence. The grant will fund the necessary infrastructure, materials, and expert guidance required to run these programs successfully.
"""

sustainability_plan_example = """
To ensure the project's long-term sustainability, we will diversify our funding sources by partnering with government agencies, corporate sponsors, and local businesses. We will also implement a mentorship program that allows trained individuals to give back by becoming educators themselves, ensuring continuous skill development in the community.
"""

# Generate proposal sections
statement_of_need = generate_text(
    f"Using the following example, write a detailed statement of need:\n\n{statement_of_need_example}\n\n"
    f"Now write a similar statement of need for this grant:\n\nProblem: {problem_statement}\n\n"
)

project_description = generate_text(
    f"Using the following example, write a detailed project description:\n\n{project_description_example}\n\n"
    f"Now write a similar project description for this grant:\n\nGoals: {goals}\n\nActivities: {planned_activities}\n\n"
)

sustainability_plan = generate_text(
    f"Using the following example, write a sustainability plan:\n\n{sustainability_plan_example}\n\n"
    f"Now write a sustainability plan for this grant based on the provided details:\n\nTimeline: {timeline}\n\n"
    f"Expected Outcomes: {expected_outcomes}\n\n"
)

# Print final grant proposal
grant_proposal = f"""
# Grant Proposal: {project_title}

## Cover Page
**Project Title:** {project_title}
**Applicant Name:** {applicant_name}

## Organization Information
**Organization Name:** {applicant_name}
**Mission Statement:** {mission_statement}

## Statement of Need
{mission_statement}

## Project Description
{project_description}

## Sustainability Plan
{sustainability_plan}
"""

print(grant_proposal)

# Save as a file
with open("grant_proposal.txt", "w", encoding="utf-8") as file:
    file.write(grant_proposal)
print("\n✅ Grant Proposal Saved as 'grant_proposal.txt'")